backend:
  name: github
  repo: CyberMalta8/wahgoods-blog
  branch: main
  auth_type: implicit
  base_url: https://wahgoods.com
  client_id: Ov23ligAiwfrZq0xgC0c

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://wahgoods.com"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
